Repository Kelompok-8-alterra/LMS-Frontend, pull requests merged in 2022-01, with the labels that each got.

#10 fix card dimension
  src/components/CourseCard.js
Labels: enhancement

#11 Feature/home page: UI nya Kelar (Static Pages)
  package-lock.json
  package.json
  src/assets/images/education.png
  src/assets/images/security.png
  src/assets/images/teaching.png
  src/assets/images/vault.png
  src/assets/images/webshop.png
  src/components/CarouselHome.js
  src/components/FirstSlide.js
  src/components/InEduDesc.js
  src/components/Layout.js
  src/components/ValuesHome.js
  src/components/courseCarousel/CourseCarousel.js
  src/pages/CourseSearch.js
  src/pages/courseEnroll/CourseEnroll.js
  src/pages/homePage/HomePage.css
  src/pages/homePage/HomePage.js
Labels: enhancement

#13 Feature/about us page: Done Static Page of About Us
  src/assets/images/developer.png
  src/components/AboutItem.js
  src/components/Layout.js
  src/pages/AboutUs.js
  src/pages/courseEnroll/CourseEnroll.js
Labels: enhancement

#14 Feature/help faq: UI static selesai, Nambahin Context juga
  src/App.js
  src/assets/images/questions.png
  src/components/CourseCard.js
  src/components/FirstSlide.js
  src/components/Layout.js
  src/contexts/GeneralContext.js
  src/pages/HelpFAQ.js
Labels: enhancement

#15 Fixing Bugs
  src/App.js
  src/customHooks/useFetch.js
  src/pages/CourseSearch.js
Labels: bug

#16 Completing CRUD Course By Teacher
  package-lock.json
  package.json
  public/assets/images/blankProfile.png
  public/assets/images/login.png
  public/assets/images/logoInEdu.png
  public/assets/images/logoInEdu.svg
  public/assets/images/secureLogin.svg
  public/assets/pallete/colors.js
  public/index.html
  src/App.js
  src/components/CourseCard.js
  src/components/CourseCardList/CourseCardList.js
  src/components/Layout.js
  src/components/NavSide.js
  src/components/responsiveAppBar/ResponsiveAppBar.js
  src/dummyData/DummyData.js
  src/pages/CourseSearch.js
  src/pages/TeacherProfile.jsx
  src/pages/teacherCourse/AddEditCard.js
  src/pages/teacherCourse/Course.api.js
  src/pages/teacherCourse/Course.hook.js
  src/pages/teacherCourse/TeacherCourse.jsx
Labels: enhancement

#17 Fix Login Authentication
  src/App.js
  src/components/CourseCardList/CourseCardList.js
  src/components/CourseCardList/CourseHook.js
  src/components/LoginForm.js
  src/components/RegistForm.js
  src/components/responsiveAppBar/ResponsiveAppBar.js
  src/pages/CourseSearch.js
  src/pages/LoginStudent.js
  src/pages/LoginTeacher.js
  src/pages/RegisterStudent.js
  src/pages/RegisterTeacher.js
  src/pages/internalServerError/InternalServerError.js
Labels: bug, enhancement

#19 Connect db/course search enroll
  src/App.js
  src/components/CourseCard.js
  src/components/CourseDescription.js
  src/components/CourseOverview.js
  src/components/Layout.js
  src/components/ReviewItem.js
  src/components/courseCarousel/CourseCarousel.js
  src/customHooks/useFetch.js
  src/pages/CourseSearch.js
  src/pages/courseEnroll/CourseEnroll.js
  src/pages/homePage/HomePage.js
  src/pages/teacherCourse/Course.hook.js
Labels: enhancement

#23 Connect db/search filter courses
  package-lock.json
  package.json
  src/components/FilterFields.js
  src/components/listCard/CourseCardList.js
  src/components/listCard/CourseHook.js
  src/contexts/GeneralContext.js
  src/pages/CourseSearch.js
Labels: enhancement

#9 Feature/StudentReading : Tampilan + Dummy data
  data/db.json
  package-lock.json
  package.json
  src/App.js
  src/components/Discussion.js
  src/components/DiscussionTeachers.js
  src/components/DisscussionStudent.js
  src/components/Layout.js
  src/components/ReadingDescription.js
  src/components/SideBar.js
  src/components/TheInstructor.js
  src/components/Title.js
  src/pages/CourseSearch.js
  src/pages/StudentReading.js
Labels: enhancement, draft

#24 feature(studentProfile): complete profile
  package-lock.json
  src/App.js
  src/components/navSideBar/NavSide.js
  src/components/navSideBar/getDataUser.js
  src/pages/studentProfile/FormEdit.jsx
  src/pages/studentProfile/StudentHook.js
  src/pages/studentProfile/StudentProfile.jsx
Labels: enhancement

#25 feature(request): completing request student and teacher
  src/App.js
  src/components/Content.js
  src/components/card/createRequest/CreateRequest.js
  src/components/card/requestCard/RequestCard.js
  src/components/card/requestCard/molecule/RowTypeStatus.js
  src/components/card/requestCard/molecule/TypeStatusMolecules.js
  src/components/navSideBar/NavSide.js
  src/customHooks/axios/putRequest/PutRequest.js
  src/customHooks/axios/useGetData.js
  src/pages/requestMail/RequestMail.jsx
  src/pages/requestMail/requestHook.js
  src/pages/teacherCourse/TeacherCourse.jsx
Labels: enhancement

#26 Feature/UI videos: Student Page Done
  package-lock.json
  package.json
  src/App.js
  src/components/BreadCrumbs.js
  src/components/Content.js
  src/components/CourseCard.js
  src/components/CourseOverview.js
  src/components/EnrolledModal.js
  src/components/SideBar.js
  src/components/StudentsFeedback.js
  src/components/StudentsReview.js
  src/components/Title.js
  src/components/TitleSideBar.js
  src/components/youtubeEmbed/youtubeEmbed.css
  src/components/youtubeEmbed/youtubeEmbed.js
  src/pages/LoginStudent.js
  src/pages/LoginTeacher.js
  src/pages/StudentReading.js
  src/pages/courseEnroll/CourseEnroll.js
  src/pages/videosPage/VideosPage.css
  src/pages/videosPage/VideosPage.js
Labels: enhancement

#27 feature(profileUpdate): remove background and add some responsive change
  src/components/LoginForm.js
  src/components/navSideBar/NavSide.js
  src/components/responsiveAppBar/ResponsiveAppBar.js
  src/contexts/GeneralContext.js
  src/pages/LoginStudent.js
  src/pages/LoginTeacher.js
  src/pages/studentProfile/FormEdit.jsx
  src/pages/studentProfile/StudentProfile.jsx
  src/pages/teacherProfile/FormEdit.jsx
Labels: enhancement

#28 feature(CI/CD): adding firebase CI/CD
  .firebaserc
  .github/workflows/main.yml
  firebase.json
  public/404.html
  public/index.html
Labels: enhancement

#30 Feature/teacher videos
  public/index.html
  src/components/CourseDescription.js
  src/components/CourseOverview.js
  src/components/FilesDescription.js
  src/components/TitleSideBar.js
  src/components/VideoFormDialogue.js
  src/components/YellowBarContent.js
  src/components/listCard/CourseCardList.js
  src/components/responsiveAppBar/ResponsiveAppBar.js
  src/contexts/GeneralContext.js
  src/pages/AddVideos.js
  src/pages/CourseSearch.js
  src/pages/courseEnroll/CourseEnroll.js
  src/pages/videosPage/VideosPage.js
Labels: enhancement

#32 Finalizing
  package-lock.json
  package.json
  src/App.js
  src/components/AddEditReadingTeacher.js
  src/components/Content.js
  src/components/CourseCard.js
  src/components/CourseDescription.js
  src/components/CourseOverview.js
  src/components/EnrollmentsTable.js
  src/components/ReadingDescription.js
  src/components/ReadingTeacherForm.js
  src/components/Title.js
  src/components/TitleSideBar.js
  src/components/YellowBarContent.js
  src/components/card/requestCard/molecule/RowTypeStatus.js
  src/components/card/requestCard/molecule/TypeStatusMolecules.js
  src/components/navSideBar/NavSide.js
  src/pages/LoginStudent.js
  src/pages/LoginTeacher.js
  src/pages/StudentReading.js
  src/pages/TeacherReading.js
  src/pages/courseEnroll/CourseEnroll.js
  src/pages/teacherCourse/TeacherCourse.jsx
  src/pages/teacherProfile/TeacherProfile.jsx
Labels: enhancement
